name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Test of cron schedule: every day at 2am and every 5 minutes for testing purposes. Adjust as needed.
    # - cron: '0 2 * * *'
    - cron: '3/5 * * * *'
  workflow_dispatch:
    inputs:
      run_mode:
        description: 'pr | nightly | full | incomplete'
        required: true
        default: 'pr'
        type: choice
        options:
          - pr
          - nightly
          - full
          - incomplete
      scenario:
        description: 'Scenario'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - direct
          - google
          - directWithConsent
          - googleWithConsent
jobs:
  e2e:
    name: E2E / ${{ github.event_name == 'workflow_dispatch' && 'manual' || github.event_name }} / ${{ github.event_name == 'schedule' && 'nightly' || github.event_name == 'workflow_dispatch' && inputs.run_mode || 'pr' }} / ${{ matrix.scenario }}
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        # scenario: ${{ fromJson(github.event_name == 'workflow_dispatch' && inputs.scenario == 'all' && '["direct","google","directWithConsent","googleWithConsent"]' || github.event_name == 'workflow_dispatch' && format('["{0}"]', inputs.scenario) || '["googleWithConsent"]') }}
        scenario: ${{ fromJson(github.event_name == 'schedule' && '["direct","google","directWithConsent","googleWithConsent"]' || github.event_name == 'workflow_dispatch' && inputs.scenario == 'all' && '["direct","google","directWithConsent","googleWithConsent"]' || github.event_name == 'workflow_dispatch' && format('["{0}"]', inputs.scenario) || '["googleWithConsent"]') }}

    env:
      PW_RUN_MODE: ${{ github.event_name == 'schedule' && 'nightly' || github.event_name == 'workflow_dispatch' && inputs.run_mode || 'pr' }}
      PW_SCENARIO: ${{ matrix.scenario }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-${{ env.PW_RUN_MODE }}-${{ env.PW_SCENARIO }}
        path: playwright-report/
        retention-days: 30
